parameters:
    flying_struct.metadata_manager.class: Flying\Struct\Metadata\MetadataManager
    flying_struct.metadata_parser.class: Flying\Struct\Metadata\AnnotationParser
    flying_struct.storage.class: Flying\Bundle\StructBundle\Storage\Storage
    flying_struct.storage_backend.array.class: Flying\Struct\Storage\ArrayBackend
    flying_struct.storage_backend.session.class: Flying\Bundle\StructBundle\Storage\SessionBackend
    flying_struct.configuration.class: Flying\Struct\Configuration

services:
    flying_struct.metadata_manager:
        class: %flying_struct.metadata_manager.class%

    flying_struct.metadata_parser:
        class: %flying_struct.metadata_parser.class%

    flying_struct.storage:
        class: %flying_struct.storage.class%
        tags:
            - { name: kernel.event_subscriber }

    flying_struct.storage_backend.array:
        class: %flying_struct.storage_backend.array.class%

    flying_struct.storage_backend.session:
        class: %flying_struct.storage_backend.session.class%
        arguments: [@session]

    flying_struct.configuration:
        class: %flying_struct.configuration.class%
        lazy: true
